name: latam_equity_dashboard
version: "1.0.0"
config-version: 2

profile: latam_equity_local

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  latam_equity_dashboard:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
